"""empty message

Revision ID: a63321dd83e3
Revises: e0a9d71c7c38
Create Date: 2019-03-24 00:01:22.313839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63321dd83e3'
down_revision = 'e0a9d71c7c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verified',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'verified',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
